### ISSUE TITLE
Logical to physical mapping

### ISSUE THREAD

**Issue by L-P-G** [collin80/TeslaBMS#10]
How are the module numbers selected? Is it first response / first numbered  or by the order of the daisy chain?

**Comment by collin80** [comment]
Yes. ;) 

The modules respond based on their position in the daisy chain and are automatically numbered that way. The first module in the chain is 1, then 2, etc. In this way they automatically get their proper address and you can easily figure out which module is which. So, yes, both first response and order of the daisy chain.
