### ISSUE TITLE
closing the main contactors inside the Tesla model-S battpack

### ISSUE THREAD

**Issue by TLS1000** [collin80/TeslaBMS#6]
Hi, I'm trying to use the kit from EVTV, for using the complete model-S battery 'as is' without opening it.
Your code does a great job reading all cell voltages and so. BUT: the main internal contactors that connect the internal batteries to the power port of the pack don't want to close. Are these main contactors controlled via code or is it purely hardware?

**Comment by collin80** [comment]
You'll have to ask Jack directly about that. I wasn't really involved in the whole pack control system. This project you've submitted the issue to is for controlling the modules inside the pack directly.

**Comment by TLS1000** [comment]
hmm...the collaboration with Jack is not working out :-) . We will try the kit on a second model-S battery to be sure, but I'm afraid we'll have to take the battery apart and go for 48V-setup.
