### ISSUE TITLE
BMS board revisions? What should I look for?

### ISSUE THREAD

**Issue by baysinger** [collin80/TeslaBMS#9]
If I were to purchase a module, is there any particular BMS revisions I should look for? Or are all the Model S modules compatible with this project?

**Comment by baysinger** [comment]
To partially answer my own question, it does indeed work with whatever this is:

![IMG_4688](https://user-images.githubusercontent.com/16112955/67114741-752dd280-f191-11e9-9f1b-f23b053d2c69.JPG)

**Comment by collin80** [comment]
Sorry, I meant to answer this long ago but completely forgot about it. Any of the Model S battery revisions should work. It appeared that they changed serial speed between revisions but only slightly and the code can support both. To my knowledge there are two main revisions of the BMS boards. One is larger than the other. But, either way they speak the same protocol and the only communication difference is a slight speed change. The old ones were 612500 and the new one something like 631000 (don't remember exactly). Other than that they work the same.

**Comment by baysinger** [comment]
Thanks. BTW, I left the baud rate alone (617647) and it's working fine. Not sure where that number comes from, though. Close enough to either speed to work, maybe?
